baseURL = "https://mfrischbutter.dev/"
languageCode = "de"
theme = "anatole"

[params]
title = "Michael Frischbutter"
author = "Michael Frischbutter"
description = "Web-Developer aus Leipzig"
profilePicture = "images/profile.jpg"
googleAnalytics = "UA-171844638-1"

[menu]
  [[menu.main]]
  name = "Startseite"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Kontakt"
  weight = 200
  identifier = "contact"
  url = "/contact/"

  [[menu.main]]
  name = "Über mich"
  weight = 300
  identifier = "about"
  url = "/about/"
